#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias ls='ls --color=auto'
alias ll='ls -l'
alias vi='vim'

export LANG=en_US.UTF-8

export REPOS=$HOME/repos

# Load Git completion
zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash
fpath=(~/.zsh $fpath)
autoload -Uz compinit && compinit

export EDITOR=vim

# nnn
export NNN_OPTS="e"  # open files using $EDITOR
source $REPOS/nnn/misc/quitcd/quitcd.bash_zsh

export PATH=$PATH:$HOME/bin

export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

export PATH=$PATH:$HOME/pkg/protoc/bin

# rust
source $HOME/.cargo/env
export PATH=$PATH:$HOME/.cargo/bin

# pip install path
export PATH=$PATH:$HOME/.local/bin

# pbcopy
alias pbcopy='xclip -selection clipboard'

# vcpkg
export PATH=$PATH:$HOME/repos/vcpkg
