#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias ls='ls --color=auto'
alias ll='ls -l'
alias vi='vim'

export LANG=en_US.UTF-8

# Load Git completion
zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash
fpath=(~/.zsh $fpath)
autoload -Uz compinit && compinit

export EDITOR=nvim
export NNN_USE_EDITOR=1
export NNN_TMPFILE="/tmp/nnn"

n()
{
        nnn "$@"

        if [ -f $NNN_TMPFILE ]; then
                . $NNN_TMPFILE
                rm -f $NNN_TMPFILE > /dev/null
        fi
}

export PATH=$PATH:$HOME/bin

export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

export PATH=$PATH:$HOME/pkg/protoc/bin

autoload -U +X bashcompinit && bashcompinit

# rust
source $HOME/.cargo/env
export PATH=$PATH:$HOME/.cargo/bin

# pip install path
export PATH=$PATH:$HOME/.local/bin

# pbcopy
alias pbcopy='xclip -selection clipboard'
