#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias ls='ls --color=auto'
alias ll='ls -l'
alias vi='nvim'

export LANG=en_US.UTF-8

export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus

# Load Git completion
zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash
fpath=(~/.zsh $fpath)
autoload -Uz compinit && compinit

export EDITOR=nvim
export NNN_USE_EDITOR=1
export NNN_TMPFILE="/tmp/nnn"

n()
{
        nnn "$@"

        if [ -f $NNN_TMPFILE ]; then
                . $NNN_TMPFILE
                rm -f $NNN_TMPFILE > /dev/null
        fi
}

export PATH=$PATH:$HOME/bin

export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin

export PATH=$PATH:$HOME/pkg/protoc/bin

source /opt/kube-ps1/kube-ps1.sh
export PROMPT='$(kube_ps1)'$PROMPT

autoload -U +X bashcompinit && bashcompinit
source '/home/oudwud/lib/azure-cli/az.completion'

source <(kubectl completion zsh)
source <(helm completion zsh)

# rust
source $HOME/.cargo/env
export PATH=$PATH:$HOME/.cargo/bin

# pip install path
export PATH=$PATH:$HOME/.local/bin

# pbcopy
alias pbcopy='xclip -selection clipboard'

# disable touchscreen
xinput | grep 'ELAN Touchscreen' | grep -Po 'id=[0-9]*' | cut -d= -f2 | xargs xinput disable
